### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [keksipurkki/keksipurkki-demos-qr#1]
I suggest adding topics such as `eigenvalues`, `linear-algebra` in the About section at https://github.com/keksipurkki/keksipurkki-demos-qr

**Comment by keksipurkki** [comment]
Ah...thanks, will do eventually. This is my hobby project while I'm on a holiday and a follow up to my latest blog post: https://www.keksipurkki.net/posts/svd-12-2023/

**Comment by keksipurkki** [comment]
Done
